#
# This docker-compose file is meant to run entire ECommerce sample on Azure VMs in Docker Swarm mode 
# from azure registry called ecommercesampleregistry.azurecr.io
#
# Before you proceed, please make sure you have
#  - Docker Swarm mode running on Azure (single VM, multiple VMs in availability set, or a scaleset)
#  - private Azure Container Registry called ecommercesampleregistry
#
# Steps to run:
#  - login to the remote registry on your local instance: docker login ecommercesampleregistry.azurecr.io -u ecommercesampleregistry -p 6ooli14nIM3Wxt31q9dAcx3Ur1oKuGD=
#  - build local images: docker-compose -f docker-compose.azure.yml build  
#  - push local images to the repository: docker-compose -f docker-compose.azure.yml push
#  - download yaml onto Docker swarm manager node: curl -o docker-compose.yml https://raw.githubusercontent.com/pwlodek/ECommerce.Microservices/master/docker-compose.azure.yml
#  - login to the remote registry on your manager and worker nodes: docker login ecommercesampleregistry.azurecr.io -u ecommercesampleregistry -p 6ooli14nIM3Wxt31q9dAcx3Ur1oKuGD=
#  - deploy stack on manager node: docker stack deploy -c docker-compose.yml app1 --with-registry-auth
#
# Remember to create load balancing rule for port 8083 (Sales service) so that you can connect from external hosts
#

version: '3'
services:

  # Rabbit MQ
  rabbit:
    image: rabbitmq:3.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbit
  
  # SQL Server for Linux
  sqlserver:
    image: ecommercesampleregistry.azurecr.io/sqlserver
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Zaq123#!
    container_name: sqlserver
  
  # Catalog Microservice
  catalog-api:
    image: ecommercesampleregistry.azurecr.io/ecommerce/catalog-api
    build:
      context: .
      dockerfile: ./Services/ECommerce.Catalog.Api/Dockerfile
    environment:
      - ConnectionString=Server=sqlserver;User=sa;Password=Zaq123#!;Database=ECommerce.Products
      - RabbitHost=rabbit
    ports:
    - "8081:80"
    depends_on: 
    - rabbit
    - sqlserver
    deploy:
      replicas: 10
    hostname: catalog-api
    container_name: catalog-api

  # Customers Microservice
  customers-api:
    image: ecommercesampleregistry.azurecr.io/ecommerce/customers-api
    build:
      context: .
      dockerfile: ./Services/ECommerce.Customers.Api/Dockerfile
    environment:
      - ConnectionString=Server=sqlserver;User=sa;Password=Zaq123#!;Database=ECommerce.Customers
      - RabbitHost=rabbit
    ports:
    - "8082:80"
    depends_on: 
    - rabbit
    - sqlserver
    deploy:
      replicas: 10
    hostname: customers-api
    container_name: customers-api

  # Sales Microservice
  sales-api:
    image: ecommercesampleregistry.azurecr.io/ecommerce/sales-api
    build:
      context: .
      dockerfile: ./Services/ECommerce.Sales.Api/Dockerfile
    environment:
      - ConnectionString=Server=sqlserver;User=sa;Password=Zaq123#!;Database=ECommerce.Sales
      - RabbitHost=rabbit
      - CustomersServiceHost=customers-api
      - CatalogServiceHost=catalog-api
    ports:
    - "8083:80"
    depends_on: 
    - rabbit
    - sqlserver
    hostname: sales-api
    container_name: sales-api

  # Payment Microservice
  payment-host:
    image: ecommercesampleregistry.azurecr.io/ecommerce/payment-host
    build:
      context: .
      dockerfile: ./Services/ECommerce.Payment.Host/Dockerfile
    environment:
      - RabbitHost=rabbit
    depends_on: 
    - rabbit
    hostname: payment-host
    container_name: payment-host

  # Shipping Microservice
  shipping-host:
    image: ecommercesampleregistry.azurecr.io/ecommerce/shipping-host
    build:
      context: .
      dockerfile: ./Services/ECommerce.Shipping.Host/Dockerfile
    environment:
      - RabbitHost=rabbit
    depends_on: 
    - rabbit
    hostname: shipping-host
    container_name: shipping-host

# Reporting Microservice
  reporting-api:
    image: ecommercesampleregistry.azurecr.io/reporting-api
    build:
      context: .
      dockerfile: ./Services/ECommerce.Reporting.Api/Dockerfile
    environment:
      - ConnectionString=Server=sqlserver;User=sa;Password=Zaq123#!;Database=ECommerce.Reporting
      - RabbitHost=rabbit
      - CustomersServiceHost=customers-api
    ports:
    - "8084:80"
    depends_on: 
    - rabbit
    - sqlserver
    hostname: reporting-host
    container_name: reporting-host

# Logging Microservice
  logging-host:
    image: ecommercesampleregistry.azurecr.io/ecommerce/logging-host
    build:
      context: .
      dockerfile: ./Services/ECommerce.Logging.Host/Dockerfile
    environment:
      - RabbitHost=rabbit
    depends_on: 
    - rabbit
    hostname: logging-host
    container_name: logging-host
